---

- name: Import Postgresql12 repo
  yum: 
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  tags:
    - patroni
  when: install is defined and install != 1
  
- name: Install PGsql12
  yum:
    name:
        - postgresql12
        - postgresql12-contrib
        - postgresql12-server
        - python-psycopg2
#       - repmgr12
    state: latest
  tags: 
    - patroni
  when: install is defined and install != 1
  debugger: on_failed
