---
- hosts: etcd
  become: True
  pre_tasks:
#    - name: Setting system hostname
#      hostname: name="{{ ansible_host }}"
#    - include: tasks/essentialsoftware.yml
  post_tasks:
#    - include: tasks/zabbix.yml
  roles:
     - etcd.role

  tasks:
#    - name: "Create directory for etcd binaries"
#      file:
#        path: /opt/etcd/bin
#        state: directory
#        owner: root
#        group: root
#        mode: 0700
