---
- hosts: pgsql

  pre_tasks:
    - name: Setting system hostname
      hostname: 
        name: "{{ inventory_hostname }}"

    - include: tasks/essentialsoftware.yml
#    - include: tasks/open-vm-tools.yml
#    - include: tasks/ntpd.yml

  post_tasks:
#    - include: tasks/zabbix.yml

  roles:
     - ssh.role
     - ansible-role-patroni
