---

- name: remove python-ldap package
  yum:
    name: 
        - python-ldap
    state: absent
  when: install is defined and install != 1

- name: Install essential software
  yum:
    name: 
        - ntpdate
        - bzip2
        - zip
        - unzip
        - openssl-devel
        - mc
        - vim
        - atop
        - wget
        - mytop
        - screen
        - net-tools
        - rsync
        - psmisc
        - gdb
        - subversion
        - htop
        - bind-utils
        - sysstat
        - nano
        - iptraf
        - nethogs
        - ngrep
        - tcpdump
        - lm_sensors
        - mtr
        - s3cmd
        - psmisc
        - gcc
        - git
        - python2-pip
        - python-devel
        - openldap-devel
    state: latest
  tags: software
  when: install is defined and install != 1
  debugger: on_failed

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
  when: install is defined and install != 1
