---

- name: "Create directory for etcd binaries"
  file:
    path: /opt/etcd/bin
    state: directory
    owner: root
    group: root
    mode: 0700
- name: "Download the tarball into the /tmp directory"
  get_url:
    url: https://storage.googleapis.com/etcd/v3.4.14/etcd-v3.4.14-linux-amd64.tar.gz
    dest: /tmp/etcd.tar.gz
    owner: root
    group: root
    mode: 0600
    force: True
- name: "Extract the contents of the tarball"
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: /opt/etcd/bin/
    owner: root
    group: root
    mode: 0600
    extra_opts:
      - --strip-components=1
    decrypt: True
    remote_src: True
- name: "Set permissions for etcd"
  file:
    path: /opt/etcd/bin/etcd
    state: file
    owner: root
    group: root
    mode: 0700
- name: "Set permissions for etcdctl"
  file:
    path: /opt/etcd/bin/etcdctl
    state: file
    owner: root
    group: root
    mode: 0700

#    - name: "Add /opt/etcd/bin/ to the $PATH environment variable"
#      lineinfile:
#        path: /etc/profile
#        line: export PATH="$PATH:/opt/etcd/bin"
#        state: present
#        create: True
#        insertafter: EOF
#    - name: "Set the ETCDCTL_API environment variable"
#      lineinfile:
#        path: /etc/profile
#        line: export ETCDCTL_API=3
#        state: present
#        create: True
#        insertafter: EOF

#- name: "Create a etcd service"
#  copy:
#    src: files/etcd.service
#    remote_src: False
#    dest: /etc/systemd/system/etcd.service
#    owner: root
#    group: root
#    mode: 0644


- name: put etcd.service systemd unit
  template: 
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
    backup: yes
  debugger: on_failed

- name: "Create a data directory"
  file:
    path: /var/lib/etcd/{{ inventory_hostname }}.etcd
    state: directory
    owner: root
    group: root
    mode: 0755
- name: "Create directory for etcd configuration"
  file:
    path: /etc/etcd
    state: directory
    owner: root
    group: root
    mode: 0755
- name: "Create configuration file for etcd"
  template:
    src: templates/etcd.conf.yaml.j2
    dest: /etc/etcd/etcd.conf.yaml
    owner: root
    group: root
    mode: 0600
- name: "Enable the etcd service"
  command: systemctl enable etcd
- name: "Start the etcd service"
  command: systemctl restart etcd
