---

#- name: "Create directory for etcd binaries"
#  file:
#    path: /opt/etcd/bin
#    state: directory
#    owner: root
#    group: root
#    mode: 0700
#  when: exists is not defined

#- name: "Download the tarball into the /tmp directory"
#  get_url:
#    url: https://storage.googleapis.com/etcd/v3.4.14/etcd-v3.4.14-linux-amd64.tar.gz
#    dest: /tmp/etcd.tar.gz
#    owner: root
#    group: root
#    mode: 0600
#    force: True
#  when: exists is not defined

#- name: "Extract the contents of the tarball"
#  unarchive:
#    src: /tmp/etcd.tar.gz
#    dest: /opt/etcd/bin/
#    owner: root
#    group: root
#    mode: 0600
#    extra_opts:
#      - --strip-components=1
#    decrypt: True
#    remote_src: True
#  when: exists is not defined

#- name: "Set permissions for etcd"
#  file:
#    path: /opt/etcd/bin/etcd
#    state: file
#    owner: root
#    group: root
#    mode: 0700
#  when: exists is not defined

#- name: "Set permissions for etcdctl"
#  file:
#    path: /opt/etcd/bin/etcdctl
#    state: file
#    owner: root
#    group: root
#    mode: 0700
#  when: exists is not defined

- name: put etcd env vars script
  template: 
    src: etcd_env.sh
    dest: /etc/profile.d/etcd_env.sh
    owner: root
    group: root
    mode: 0755
    backup: yes
  debugger: on_failed

- name: put etcd.service systemd unit
  template: 
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
    backup: yes
  debugger: on_failed

- name: "Stop the etcd service"
  command: systemctl stop etcd
- name: "Create a data directory"
  file:
    path: /var/lib/etcd/{{ inventory_hostname }}.etcd
    state: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - absent
    - directory

- name: "Create directory for etcd configuration"
  file:
    path: /etc/etcd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Create configuration file for etcd"
  template:
    src: templates/etcd.conf.yaml.j2
    dest: /etc/etcd/etcd.conf.yaml
    owner: root
    group: root
    mode: 0600
  debugger: on_failed

- name: "Enable the etcd service"
  command: systemctl enable etcd
- name: "Start the etcd service"
  command: systemctl restart etcd
